### Lab 3 CS_370
### Makefile for Symbol Table
### Ryan Schwarzkopf
### Feb 3, 2023

# dependencies: symtable.c -> symtable.h
# description: makefile compiles symtable.c into lab3 executable

all: lab3

lab3: symtable.c symtable.h
	gcc symtable.c -o lab3

clean:
	rm -f lab3